title: Pyxona
author: Admin
email: contact@pyxona.com
description: 

# social links
twitter_username: pyxona
rss: rss
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
# linkedin_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 

# Mastodon instances
# mastodon:
# - username: 
#   instance: example.com
# - username: 
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- portfolio.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
